<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"><title>https://akasurde.github.io - Python, MacOSX</title><link href="https://akasurde.github.io/" rel="alternate"></link><link href="https://akasurde.github.io/feeds/python-macosx.atom.xml" rel="self"></link><id>https://akasurde.github.io/</id><updated>2017-03-17T12:03:00+05:30</updated><subtitle>Developer, Hacker</subtitle><entry><title>Python - UTF-8 ValueError</title><link href="https://akasurde.github.io/python-macosx-utf8-valuerror.html" rel="alternate"></link><published>2017-03-17T12:03:00+05:30</published><updated>2016-03-17T12:03:00+05:30</updated><author><name>Abhijeet Kasurde</name></author><id>tag:akasurde.github.io,2017-03-17:/python-macosx-utf8-valuerror.html</id><summary type="html">&lt;p&gt;Mac OS X: ValueError: unknown locale: UTF-8 in Python&lt;/p&gt;</summary><content type="html">&lt;p&gt;If you get the error on MacOS X, here's the quick fix - add these lines to your &lt;code&gt;~/.bash_profile&lt;/code&gt;:&lt;/p&gt;
&lt;pre&gt;
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
&lt;/pre&gt;</content><category term="Python, MacOSX"></category><category term="Python"></category><category term="osx"></category><category term="mac"></category><category term="django"></category><category term="utf8"></category><category term="valueerror"></category><category term="locale"></category></entry></feed>